export const paths = {
  introduceYourself: '/introduce-yourself',
  interests: '/interests',
  onboarding: '/onboarding',
  joinSpace: '/join-space',
  post: '/post/:postId',
  privatePost: '/private-post/:postId',
  invitationQR: '/invitation-qr/:spaceId',
  spaceDetails: '/spaces/details/:spaceId',
  createSpace: '/create-space',
  createSpaceDetails: '/create-space/details',
  createSpaceInterests: '/create-space/space-interests',
  createSpaceFinal: '/create-space/final',
  appreciate: '/appreciate/:appreciateId',
  qrOptions: '/get-appreciate/qr-options',
  transactionDetails: '/list/transactions/:transactionId',
  userDetails: '/more/:userId',
  userLocation: '/more/:userId/location',
  home: '/home',
  spaces: '/spaces',
  spaceSettings: '/spaces/space-settings',
  spaceSettingsFollowings: '/spaces/space-settings/followings',
  spaceSettingsInvitations: '/spaces/space-settings/invitations',
  map: '/map',
  more: '/more',
  listing: '/more/listing',
  accounts: '/more/accounts',
  transactionsList: '/more/transactions',
  language: '/more/language',
  pendingTransactions: '/more/pending-transactions',
} as const;

export type PathKey = keyof typeof paths;
export type PathValue = (typeof paths)[PathKey];
