export const paths = {
  introduceYourself: '/introduce-yourself',
  interests: '/interests',
  onboarding: '/onboarding',
  joinGroup: '/join-group',
  post: '/post/:postId',
  privatePost: '/private-post/:postId',
  invitationQR: '/invitation-qr/:groupId',
  inviteUser: '/invite-user/:groupId',
  groupDetails: '/groups/details/:groupId',
  createGroup: '/create-group',
  createGroupDetails: '/create-group/details',
  createGroupInterests: '/create-group/group-interests',
  createGroupFinal: '/create-group/final',
  thankYou: '/thank-you',
  phoneNumberAppreciate: '/phone-number-appreciate',
  scanQRCode: '/scan-qr-code',
  appreciate: '/appreciate/:appreciateId',
  getAppreciate: '/get-appreciate',
  qrOptions: '/get-appreciate/qr-options',
  transactionDetails: '/list/transactions/:transactionId',
  userDetails: '/more/:userId',
  userLocation: '/more/:userId/location',
  home: '/home',
  groups: '/groups',
  groupSettings: '/groups/group-settings',
  groupSettingsFollowings: '/groups/group-settings/followings',
  groupSettingsInvitations: '/groups/group-settings/invitations',
  map: '/map',
  more: '/more',
  listing: '/more/listing',
  accounts: '/more/accounts',
  transactionsList: '/more/transactions',
  language: '/more/language',
  pendingTransactions: '/more/pending-transactions',
} as const;

export type PathKey = keyof typeof paths;
export type PathValue = (typeof paths)[PathKey];
